[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#6B6BFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#FFFFFF"
font = "sans serif"

[server]
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
